export const localizers = {
  en: {
    valueLabel: "Value",
    fieldLabel: "Field",
    operatorLabel: "Operator",
    funcLabel: "Function",
    lockLabel: "Lock",
    lockedLabel: "Locked",
    deleteLabel: null,
    addGroupLabel: "Add group",
    addRuleLabel: "Add rule",
    addSubRuleLabel: "Add sub rule",
    delGroupLabel: null,
    notLabel: "Not",
    valueSourcesPopupTitle: "Select value source",
    removeRuleConfirmOptions: {
      title: "Are you sure delete this rule?",
      okText: "Yes",
      okType: "danger",
      cancelText: "Cancel",
    },
    removeGroupConfirmOptions: {
      title: "Are you sure delete this group?",
      okText: "Yes",
      okType: "danger",
      cancelText: "Cancel",
    },
    typeOptions: {
      attribute: "Attribute",
      folder: "Folder",
      dataTree: "Data tree",
    },
    placeholders: {
      fieldSelectPlaceholder: "Type",
      valuePlaceholder: "Value",
      fieldPlaceholder: "Attribute",
      funcPlaceholder: "Select function",
      operatorPlaceholder: "Select operator",
    },
    treeModal: {
      title: "Select 4D Node in Data Tree",
      okText: "Yes",
      okType: "danger",
      cancelText: "Cancel",
    },
  },
  fi: {
    valueLabel: "Arvo",
    fieldLabel: "Kenttä",
    operatorLabel: "Operaattori",
    funcLabel: "Toiminto",
    lockLabel: "Lukitse",
    lockedLabel: "Lukittu",
    deleteLabel: null,
    addGroupLabel: "Lisää ryhmä",
    addRuleLabel: "Lisää sääntö",
    addSubRuleLabel: "Lisää alisääntö",
    delGroupLabel: null,
    notLabel: "Ei",
    valueSourcesPopupTitle: "Valitse arvon lähde",
    removeRuleConfirmOptions: {
      title: "Haluatko varmasti poistaa tämän säännön?",
      okText: "Kyllä",
      okType: "vaara",
      cancelText: "Peruuta",
    },
    removeGroupConfirmOptions: {
      title: "Haluatko varmasti poistaa tämän ryhmän?",
      okText: "Kyllä",
      okType: "vaara",
      cancelText: "Peruuta",
    },
    typeOptions: {
      attribute: "Attribuutti",
      folder: "Kansio",
      dataTree: "Datan puu",
    },
    placeholders: {
      fieldSelectPlaceholder: "Tyyppi",
      valuePlaceholder: "Arvo",
      fieldPlaceholder: "Attribuutti",
      funcPlaceholder: "Valitse toiminto",
      operatorPlaceholder: "Valitse operaattori",
    },
    treeModal: {
      title: "Valitse 4D-solmu datapuusta",
      okText: "Kyllä",
      okType: "vaara",
      cancelText: "Peruuta",
    },
  },
};
